PERMISSIONS: dict[str, str] = {
    "accounts:read": "Read owned or assigned bank accounts",
    "accounts:create": "Create bank account records",
    "accounts:update": "Update bank account records",
    "accounts:delete": "Delete bank account records",
    "transactions:read": "Read owned or assigned transactions",
    "transactions:create": "Create transactions",
    "transactions:update": "Update transactions",
    "transactions:delete": "Delete transactions",
    "budgets:read": "Read budgets",
    "budgets:create": "Create budgets",
    "budgets:update": "Update budgets",
    "budgets:delete": "Delete budgets",
    "dashboard:read": "Read banking dashboard",
    "reports:read": "Read reports",
    "reports:export": "Export reports",
    "analytics:read": "Read analytics",
    "analytics:calculate": "Run banking calculations",
    "organizations:read": "Read business banking organizations",
    "organizations:create": "Create business banking organizations",
    "organizations:update": "Update business banking organizations",
    "memberships:read": "Read organization memberships",
    "memberships:manage": "Manage organization memberships",
    "entitlements:read": "Read account entitlements",
    "entitlements:manage": "Manage account entitlements",
    "beneficiaries:read": "Read beneficiaries and payees",
    "beneficiaries:create": "Create beneficiaries and payees",
    "beneficiaries:update": "Update beneficiaries and payees",
    "transfers:read": "Read money movement transfers",
    "transfers:create": "Create transfer instructions",
    "transfers:submit": "Submit transfer instructions",
    "transfers:approve": "Approve pending transfer instructions",
    "transfers:cancel": "Cancel eligible transfer instructions",
    "approvals:read": "Read approval policies and requests",
    "approvals:manage": "Manage approval policies",
    "approvals:decide": "Approve or reject approval requests",
    "risk:read": "Read risk alerts",
    "risk:manage": "Manage risk alerts",
    "compliance:read": "Read compliance cases",
    "compliance:manage": "Manage compliance cases",
    "ledger:read": "Read ledger entries, holds, and available balances",
    "ledger:manage": "Create operational ledger snapshots",
    "statements:read": "Read generated account statements",
    "statements:generate": "Generate account statements",
    "notifications:read": "Read own banking notifications",
    "cards:read": "Read issued cards and authorizations",
    "cards:issue": "Issue cards",
    "cards:manage": "Manage card status and controls",
    "cards:authorize": "Create or reverse card authorizations",
    "cards:capture": "Capture approved card authorizations",
    "disputes:read": "Read card and transaction disputes",
    "disputes:create": "Open disputes",
    "disputes:manage": "Manage dispute lifecycle",
    "users:read": "Read users",
    "users:update": "Update users",
    "admin:metrics": "Read admin metrics",
    "audit:read": "Read audit logs and security events",
    "sessions:manage": "Manage own sessions",
    "sessions:manage_any": "Manage any user session",
    "iam:manage": "Manage roles and permissions",
}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": list(PERMISSIONS),
    "bank_admin": [
        "accounts:read", "accounts:create", "accounts:update", "transactions:read",
        "budgets:read", "dashboard:read", "reports:read", "reports:export",
        "analytics:read", "organizations:read", "organizations:create", "organizations:update",
        "memberships:read", "memberships:manage", "entitlements:read", "entitlements:manage",
        "beneficiaries:read", "beneficiaries:create", "beneficiaries:update",
        "transfers:read", "transfers:create", "transfers:submit", "transfers:approve", "transfers:cancel",
        "approvals:read", "approvals:manage", "approvals:decide",
        "risk:read", "risk:manage", "compliance:read", "compliance:manage",
        "ledger:read", "ledger:manage", "statements:read", "statements:generate", "notifications:read",
        "cards:read", "cards:issue", "cards:manage", "cards:authorize", "cards:capture",
        "disputes:read", "disputes:create", "disputes:manage",
        "users:read", "admin:metrics", "audit:read", "sessions:manage_any",
    ],
    "compliance_officer": [
        "accounts:read", "transactions:read", "organizations:read", "memberships:read", "entitlements:read",
        "beneficiaries:read", "transfers:read", "reports:read", "reports:export", "audit:read", "users:read",
        "approvals:read", "risk:read", "risk:manage", "compliance:read", "compliance:manage",
        "ledger:read", "statements:read", "notifications:read",
        "cards:read", "disputes:read", "disputes:manage",
    ],
    "risk_manager": [
        "accounts:read", "transactions:read", "dashboard:read", "analytics:read", "reports:read",
        "organizations:read", "entitlements:read", "beneficiaries:read", "transfers:read",
        "approvals:read", "risk:read", "risk:manage", "compliance:read", "compliance:manage",
        "ledger:read", "statements:read", "notifications:read",
        "cards:read", "disputes:read", "disputes:manage",
    ],
    "support_agent": [
        "accounts:read", "transactions:read", "organizations:read", "beneficiaries:read", "transfers:read",
        "cards:read", "disputes:read", "disputes:manage", "users:read",
    ],
    "business_owner": [
        "accounts:read", "accounts:create", "accounts:update", "transactions:read", "transactions:create",
        "budgets:read", "budgets:create", "budgets:update", "dashboard:read", "reports:read", "reports:export",
        "analytics:read", "analytics:calculate", "organizations:read", "organizations:create", "organizations:update",
        "memberships:read", "memberships:manage", "entitlements:read", "entitlements:manage",
        "beneficiaries:read", "beneficiaries:create", "beneficiaries:update",
        "transfers:read", "transfers:create", "transfers:submit", "transfers:approve", "transfers:cancel",
        "approvals:read", "approvals:manage", "approvals:decide",
        "ledger:read", "ledger:manage", "statements:read", "statements:generate", "notifications:read",
        "cards:read", "cards:issue", "cards:manage", "cards:authorize", "cards:capture",
        "disputes:read", "disputes:create",
        "sessions:manage",
    ],
    "business_admin": [
        "accounts:read", "accounts:create", "accounts:update", "transactions:read", "transactions:create",
        "budgets:read", "budgets:create", "budgets:update", "dashboard:read", "reports:read", "analytics:read",
        "organizations:read", "organizations:update", "memberships:read", "memberships:manage",
        "entitlements:read", "entitlements:manage", "beneficiaries:read", "beneficiaries:create", "beneficiaries:update",
        "transfers:read", "transfers:create", "transfers:submit", "transfers:approve", "transfers:cancel",
        "approvals:read", "approvals:decide",
        "ledger:read", "statements:read", "statements:generate", "notifications:read",
        "cards:read", "cards:issue", "cards:manage", "cards:authorize", "cards:capture",
        "disputes:read", "disputes:create",
        "sessions:manage",
    ],
    "accountant": [
        "accounts:read", "transactions:read", "budgets:read", "reports:read", "reports:export", "analytics:read",
        "organizations:read", "memberships:read", "entitlements:read", "beneficiaries:read",
        "transfers:read", "approvals:read", "ledger:read", "statements:read", "statements:generate", "notifications:read",
        "cards:read", "disputes:read",
    ],
    "customer": [
        "accounts:read", "accounts:create", "accounts:update", "accounts:delete",
        "transactions:read", "transactions:create", "transactions:update", "transactions:delete",
        "budgets:read", "budgets:create", "budgets:update", "budgets:delete",
        "dashboard:read", "reports:read", "reports:export", "analytics:read", "analytics:calculate",
        "beneficiaries:read", "beneficiaries:create", "beneficiaries:update",
        "transfers:read", "transfers:create", "transfers:submit", "transfers:cancel",
        "ledger:read", "statements:read", "statements:generate", "notifications:read",
        "cards:read", "cards:issue", "cards:manage", "cards:authorize", "cards:capture",
        "disputes:read", "disputes:create", "sessions:manage",
    ],
    "read_only": [
        "accounts:read", "transactions:read", "budgets:read", "dashboard:read", "reports:read", "analytics:read",
        "organizations:read", "memberships:read", "entitlements:read", "beneficiaries:read", "transfers:read",
        "ledger:read", "statements:read", "notifications:read", "cards:read", "disputes:read",
    ],
}
